### Global configuration.

default_game: "Battlefield 1"

### Credentials for Discord and other services.

token: "blank"
owner_id: 0000

command_prefix: "!"

anilist_client_id: "id"
anilist_client_secret: "secret"

mal_username: "username"
mal_password: "password;"

twitter_key: "key"
twitter_secret: "secret"