### Global configuration.
global:
    default_game: "Battlefield 1"


    ### Credentials for Discord
    token: "blank"

    command_prefix: "!"

    ### Refresh rate for timed modules
    refresh_rate: 30


### Module configuration
anilist:
    anilist_client_id: "id"
    anilist_client_secret: "secret"

mal:
    mal_username: "username"
    mal_password: "password;"

twitter:
    twitter_key: "key"
    twitter_secret: "secret"