### Global configuration.
global:
    default_game: "Battlefield 1"


    ### Credentials for Discord
    token: "blank"

    command_prefix: "!"

### Module configuration
anilist:
    client_id: "id"
    client_secret: "secret"

mal:
    username: "username"
    password: "password;"

twitter:
    client_key: "key"
    client_secret: "secret"

    color:
        - 33
        - 155
        - 243

    refresh_rate: 30

reddit:
    color:
        - 255
        - 152
        - 0

    compact_keywords:
        - "spoiler"
        - "nsfw"

    filter_keywords: []
    refresh_rate: 30

animefeed:
    refresh_rate: 30