### Global configuration.
global:
    default_game: "Battlefield 1"


    ### Credentials for Discord
    token: "blank"

    command_prefix: "!"

    ### Refresh rate for timed modules
    refresh_rate: 30


### Module configuration
anilist:
    client_id: "id"
    client_secret: "secret"

mal:
    username: "username"
    password: "password;"

twitter:
    key: "key"
    secret: "secret"