### Global configuration.
global:
    default_game: "Battlefield 1"

    ### Credentials for Discord
    token: "blank"

    command_prefix: "!"

    ### Refresh rate for timed services
    refresh_rate: 30

    ### Channel id for logging to a Discord channel
    logging_channel_id: "000000000000000000"

    ###Optional Unicode logging
    unicode_logging: false

    database:
        ### Possible options are SQLServer, PostgreSQL
        provider: "provider"
        ### The provider specific connect string
        connect_string: "connect_string"

### Module configuration
anilist:
    client_id: "id"
    client_secret: "secret"

    color:
        - 2
        - 169
        - 255

mal:
    username: "username"
    password: "password"

    color:
        - 63
        - 81
        - 181

twitter:
    client_key: "key"
    client_secret: "secret"

    color:
        - 33
        - 155
        - 243

reddit:
    color:
        - 255
        - 152
        - 0

    compact_keywords:
        - "spoiler"
        - "nsfw"

    filter_keywords: []